### ISSUE TITLE
Feature request: allow multiple input files or stdin as input

### ISSUE THREAD

**Issue by funkyfuture** [pbogdan/ngx-top#3]
ciao, we're writing nginx logfiles per hostname. hence `ngx-top` can't give us metrics for the whole server.

either the ability to provide multiple input files - without wildcards that wouldn't be fun - or reading from stdin would make the tool useful for us. had you considered one of these features yet? would you be interested?

**Comment by pbogdan** [comment]
I haven't really thought about it but it would definitely be a nice feature to have.

I'll take a look and see what would be needed to implement this in some form.

**Comment by pbogdan** [comment]
Just released v0.3.0.0 with support for monitoring multiple files. Will try and see if adding support for reading from stdin would be feasible as that could be nice to have as well.

**Comment by funkyfuture** [comment]
cool, thank you. it doesn't support globbing though, right? shall i commit an example invokation with `find` to the `REAMDE`?

**Comment by pbogdan** [comment]
Hmm, how are you invoking `ngx-top`? Any globbing should be handled by your shell which will expand the arguments before they are passed to `ngx-top`. So saying `ngx-top log*` should be perfectly fine (and does indeed work) and is handled by your shell.

**Comment by funkyfuture** [comment]
i won't be able to check it out too soon. we can close this issue, if you want.

regarding the globbing by shell i'm a little irritated as i expanded wildcards myself when implementing a cli-tool with Python.

**Comment by funkyfuture** [comment]
cool, this seems to work as you expected.

`ngx-top` seems to hang for a while before it outputs something. but i can reproduce this with the prior version and a single file as well.
